services:
  back:
    build: ./packages/back
    ports:
      - "4000:4000"
    networks:
      - galactus-network

  front:
    build: ./packages/front
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - galactus-network

networks:
  galactus-network:
    driver: bridge
